server:
  address:     "0.0.0.0:8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  # link: "mysql:root:MYSQL_PASSWORD@tcp(db:3306)/goframe_serverless_template"
  debug: true

gfcli:
  gen:
    dao:
    - link:     "mysql:root:MYSQL_PASSWORD@tcp(db:3306)/goframe_serverless_template"
      # tables: ""
      jsonCase: "CamelLower"