version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/root/project/goframe-serverless-template
    stdin_open: true
    tty: true
  db:
    image: mysql/mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_PASSWORD"
      MYSQL_ROOT_HOST: "%"
    # docker exec -it *** sh && mysql -pMYSQL_PASSWORD