// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-23 14:45:57
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Task is the golang structure for table task.
type Task struct {
	Id       uint        `json:"id"       ` // ID
	CreateAt *gtime.Time `json:"createAt" ` // Created Time
	UpdateAt *gtime.Time `json:"updateAt" ` // Updated Time
	DeleteAt *gtime.Time `json:"deleteAt" ` // Deleted Time
	Title    string      `json:"title"    ` // title
	IsDone   int         `json:"isDone"   ` // is done
}
